// source: protos/deviceEvents.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.cattlechain.AnimalMonitoring', null, global);
goog.exportSymbol('proto.cattlechain.AnimalWelfareIndicators', null, global);
goog.exportSymbol('proto.cattlechain.DeviceEvents', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cattlechain.DeviceEvents = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cattlechain.DeviceEvents.repeatedFields_, null);
};
goog.inherits(proto.cattlechain.DeviceEvents, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cattlechain.DeviceEvents.displayName = 'proto.cattlechain.DeviceEvents';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cattlechain.AnimalMonitoring = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cattlechain.AnimalMonitoring, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cattlechain.AnimalMonitoring.displayName = 'proto.cattlechain.AnimalMonitoring';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cattlechain.AnimalWelfareIndicators = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cattlechain.AnimalWelfareIndicators, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cattlechain.AnimalWelfareIndicators.displayName = 'proto.cattlechain.AnimalWelfareIndicators';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cattlechain.DeviceEvents.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cattlechain.DeviceEvents.prototype.toObject = function(opt_includeInstance) {
  return proto.cattlechain.DeviceEvents.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cattlechain.DeviceEvents} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.DeviceEvents.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    monitoringList: jspb.Message.toObjectList(msg.getMonitoringList(),
    proto.cattlechain.AnimalMonitoring.toObject, includeInstance),
    indicatorsList: jspb.Message.toObjectList(msg.getIndicatorsList(),
    proto.cattlechain.AnimalWelfareIndicators.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cattlechain.DeviceEvents}
 */
proto.cattlechain.DeviceEvents.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cattlechain.DeviceEvents;
  return proto.cattlechain.DeviceEvents.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cattlechain.DeviceEvents} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cattlechain.DeviceEvents}
 */
proto.cattlechain.DeviceEvents.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.cattlechain.AnimalMonitoring;
      reader.readMessage(value,proto.cattlechain.AnimalMonitoring.deserializeBinaryFromReader);
      msg.addMonitoring(value);
      break;
    case 3:
      var value = new proto.cattlechain.AnimalWelfareIndicators;
      reader.readMessage(value,proto.cattlechain.AnimalWelfareIndicators.deserializeBinaryFromReader);
      msg.addIndicators(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cattlechain.DeviceEvents.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cattlechain.DeviceEvents.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cattlechain.DeviceEvents} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.DeviceEvents.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMonitoringList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.cattlechain.AnimalMonitoring.serializeBinaryToWriter
    );
  }
  f = message.getIndicatorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.cattlechain.AnimalWelfareIndicators.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.cattlechain.DeviceEvents.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.DeviceEvents} returns this
 */
proto.cattlechain.DeviceEvents.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated AnimalMonitoring monitoring = 2;
 * @return {!Array<!proto.cattlechain.AnimalMonitoring>}
 */
proto.cattlechain.DeviceEvents.prototype.getMonitoringList = function() {
  return /** @type{!Array<!proto.cattlechain.AnimalMonitoring>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cattlechain.AnimalMonitoring, 2));
};


/**
 * @param {!Array<!proto.cattlechain.AnimalMonitoring>} value
 * @return {!proto.cattlechain.DeviceEvents} returns this
*/
proto.cattlechain.DeviceEvents.prototype.setMonitoringList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.cattlechain.AnimalMonitoring=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cattlechain.AnimalMonitoring}
 */
proto.cattlechain.DeviceEvents.prototype.addMonitoring = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.cattlechain.AnimalMonitoring, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cattlechain.DeviceEvents} returns this
 */
proto.cattlechain.DeviceEvents.prototype.clearMonitoringList = function() {
  return this.setMonitoringList([]);
};


/**
 * repeated AnimalWelfareIndicators indicators = 3;
 * @return {!Array<!proto.cattlechain.AnimalWelfareIndicators>}
 */
proto.cattlechain.DeviceEvents.prototype.getIndicatorsList = function() {
  return /** @type{!Array<!proto.cattlechain.AnimalWelfareIndicators>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cattlechain.AnimalWelfareIndicators, 3));
};


/**
 * @param {!Array<!proto.cattlechain.AnimalWelfareIndicators>} value
 * @return {!proto.cattlechain.DeviceEvents} returns this
*/
proto.cattlechain.DeviceEvents.prototype.setIndicatorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.cattlechain.AnimalWelfareIndicators=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cattlechain.AnimalWelfareIndicators}
 */
proto.cattlechain.DeviceEvents.prototype.addIndicators = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.cattlechain.AnimalWelfareIndicators, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cattlechain.DeviceEvents} returns this
 */
proto.cattlechain.DeviceEvents.prototype.clearIndicatorsList = function() {
  return this.setIndicatorsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cattlechain.AnimalMonitoring.prototype.toObject = function(opt_includeInstance) {
  return proto.cattlechain.AnimalMonitoring.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cattlechain.AnimalMonitoring} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.AnimalMonitoring.toObject = function(includeInstance, msg) {
  var f, obj = {
    monitoring: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cattlechain.AnimalMonitoring}
 */
proto.cattlechain.AnimalMonitoring.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cattlechain.AnimalMonitoring;
  return proto.cattlechain.AnimalMonitoring.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cattlechain.AnimalMonitoring} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cattlechain.AnimalMonitoring}
 */
proto.cattlechain.AnimalMonitoring.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMonitoring(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cattlechain.AnimalMonitoring.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cattlechain.AnimalMonitoring.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cattlechain.AnimalMonitoring} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.AnimalMonitoring.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMonitoring();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string monitoring = 1;
 * @return {string}
 */
proto.cattlechain.AnimalMonitoring.prototype.getMonitoring = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.AnimalMonitoring} returns this
 */
proto.cattlechain.AnimalMonitoring.prototype.setMonitoring = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cattlechain.AnimalWelfareIndicators.prototype.toObject = function(opt_includeInstance) {
  return proto.cattlechain.AnimalWelfareIndicators.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cattlechain.AnimalWelfareIndicators} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.AnimalWelfareIndicators.toObject = function(includeInstance, msg) {
  var f, obj = {
    indicator: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cattlechain.AnimalWelfareIndicators}
 */
proto.cattlechain.AnimalWelfareIndicators.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cattlechain.AnimalWelfareIndicators;
  return proto.cattlechain.AnimalWelfareIndicators.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cattlechain.AnimalWelfareIndicators} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cattlechain.AnimalWelfareIndicators}
 */
proto.cattlechain.AnimalWelfareIndicators.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIndicator(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cattlechain.AnimalWelfareIndicators.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cattlechain.AnimalWelfareIndicators.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cattlechain.AnimalWelfareIndicators} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.AnimalWelfareIndicators.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIndicator();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string indicator = 1;
 * @return {string}
 */
proto.cattlechain.AnimalWelfareIndicators.prototype.getIndicator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.AnimalWelfareIndicators} returns this
 */
proto.cattlechain.AnimalWelfareIndicators.prototype.setIndicator = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.cattlechain);
