// source: protos/farmIdentity.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.cattlechain.FarmIdentity', null, global);
goog.exportSymbol('proto.cattlechain.FarmIdentity.ADDRESS', null, global);
goog.exportSymbol('proto.cattlechain.FarmIdentity.CONTACTPOINT', null, global);
goog.exportSymbol('proto.cattlechain.FarmIdentity.LOCATION', null, global);
goog.exportSymbol('proto.cattlechain.FarmIdentity.RELATEDSOURCE', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cattlechain.FarmIdentity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cattlechain.FarmIdentity.repeatedFields_, null);
};
goog.inherits(proto.cattlechain.FarmIdentity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cattlechain.FarmIdentity.displayName = 'proto.cattlechain.FarmIdentity';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cattlechain.FarmIdentity.CONTACTPOINT, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cattlechain.FarmIdentity.CONTACTPOINT.displayName = 'proto.cattlechain.FarmIdentity.CONTACTPOINT';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cattlechain.FarmIdentity.ADDRESS = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cattlechain.FarmIdentity.ADDRESS, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cattlechain.FarmIdentity.ADDRESS.displayName = 'proto.cattlechain.FarmIdentity.ADDRESS';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cattlechain.FarmIdentity.LOCATION = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cattlechain.FarmIdentity.LOCATION.repeatedFields_, null);
};
goog.inherits(proto.cattlechain.FarmIdentity.LOCATION, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cattlechain.FarmIdentity.LOCATION.displayName = 'proto.cattlechain.FarmIdentity.LOCATION';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cattlechain.FarmIdentity.RELATEDSOURCE, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cattlechain.FarmIdentity.RELATEDSOURCE.displayName = 'proto.cattlechain.FarmIdentity.RELATEDSOURCE';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cattlechain.FarmIdentity.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cattlechain.FarmIdentity.prototype.toObject = function(opt_includeInstance) {
  return proto.cattlechain.FarmIdentity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cattlechain.FarmIdentity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, ""),
    datacreated: jspb.Message.getFieldWithDefault(msg, 3, ""),
    datamodified: jspb.Message.getFieldWithDefault(msg, 4, ""),
    name: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    contactpoint: (f = msg.getContactpoint()) && proto.cattlechain.FarmIdentity.CONTACTPOINT.toObject(includeInstance, f),
    ownedby: jspb.Message.getFieldWithDefault(msg, 8, ""),
    address: (f = msg.getAddress()) && proto.cattlechain.FarmIdentity.ADDRESS.toObject(includeInstance, f),
    location: (f = msg.getLocation()) && proto.cattlechain.FarmIdentity.LOCATION.toObject(includeInstance, f),
    relatedsourceList: jspb.Message.toObjectList(msg.getRelatedsourceList(),
    proto.cattlechain.FarmIdentity.RELATEDSOURCE.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cattlechain.FarmIdentity}
 */
proto.cattlechain.FarmIdentity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cattlechain.FarmIdentity;
  return proto.cattlechain.FarmIdentity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cattlechain.FarmIdentity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cattlechain.FarmIdentity}
 */
proto.cattlechain.FarmIdentity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatacreated(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatamodified(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = new proto.cattlechain.FarmIdentity.CONTACTPOINT;
      reader.readMessage(value,proto.cattlechain.FarmIdentity.CONTACTPOINT.deserializeBinaryFromReader);
      msg.setContactpoint(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnedby(value);
      break;
    case 9:
      var value = new proto.cattlechain.FarmIdentity.ADDRESS;
      reader.readMessage(value,proto.cattlechain.FarmIdentity.ADDRESS.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 10:
      var value = new proto.cattlechain.FarmIdentity.LOCATION;
      reader.readMessage(value,proto.cattlechain.FarmIdentity.LOCATION.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    case 11:
      var value = new proto.cattlechain.FarmIdentity.RELATEDSOURCE;
      reader.readMessage(value,proto.cattlechain.FarmIdentity.RELATEDSOURCE.deserializeBinaryFromReader);
      msg.addRelatedsource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cattlechain.FarmIdentity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cattlechain.FarmIdentity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cattlechain.FarmIdentity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDatacreated();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDatamodified();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getContactpoint();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.cattlechain.FarmIdentity.CONTACTPOINT.serializeBinaryToWriter
    );
  }
  f = message.getOwnedby();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.cattlechain.FarmIdentity.ADDRESS.serializeBinaryToWriter
    );
  }
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.cattlechain.FarmIdentity.LOCATION.serializeBinaryToWriter
    );
  }
  f = message.getRelatedsourceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.cattlechain.FarmIdentity.RELATEDSOURCE.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.prototype.toObject = function(opt_includeInstance) {
  return proto.cattlechain.FarmIdentity.CONTACTPOINT.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cattlechain.FarmIdentity.CONTACTPOINT} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.toObject = function(includeInstance, msg) {
  var f, obj = {
    email: jspb.Message.getFieldWithDefault(msg, 1, ""),
    telephone: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cattlechain.FarmIdentity.CONTACTPOINT}
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cattlechain.FarmIdentity.CONTACTPOINT;
  return proto.cattlechain.FarmIdentity.CONTACTPOINT.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cattlechain.FarmIdentity.CONTACTPOINT} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cattlechain.FarmIdentity.CONTACTPOINT}
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTelephone(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cattlechain.FarmIdentity.CONTACTPOINT.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cattlechain.FarmIdentity.CONTACTPOINT} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTelephone();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string email = 1;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity.CONTACTPOINT} returns this
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string telephone = 2;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.prototype.getTelephone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity.CONTACTPOINT} returns this
 */
proto.cattlechain.FarmIdentity.CONTACTPOINT.prototype.setTelephone = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cattlechain.FarmIdentity.ADDRESS.prototype.toObject = function(opt_includeInstance) {
  return proto.cattlechain.FarmIdentity.ADDRESS.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cattlechain.FarmIdentity.ADDRESS} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.ADDRESS.toObject = function(includeInstance, msg) {
  var f, obj = {
    addresslocality: jspb.Message.getFieldWithDefault(msg, 1, ""),
    addresscountry: jspb.Message.getFieldWithDefault(msg, 2, ""),
    streetaddress: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cattlechain.FarmIdentity.ADDRESS}
 */
proto.cattlechain.FarmIdentity.ADDRESS.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cattlechain.FarmIdentity.ADDRESS;
  return proto.cattlechain.FarmIdentity.ADDRESS.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cattlechain.FarmIdentity.ADDRESS} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cattlechain.FarmIdentity.ADDRESS}
 */
proto.cattlechain.FarmIdentity.ADDRESS.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddresslocality(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddresscountry(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStreetaddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cattlechain.FarmIdentity.ADDRESS.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cattlechain.FarmIdentity.ADDRESS.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cattlechain.FarmIdentity.ADDRESS} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.ADDRESS.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddresslocality();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddresscountry();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStreetaddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string addressLocality = 1;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.ADDRESS.prototype.getAddresslocality = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity.ADDRESS} returns this
 */
proto.cattlechain.FarmIdentity.ADDRESS.prototype.setAddresslocality = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string addressCountry = 2;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.ADDRESS.prototype.getAddresscountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity.ADDRESS} returns this
 */
proto.cattlechain.FarmIdentity.ADDRESS.prototype.setAddresscountry = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string streetAddress = 3;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.ADDRESS.prototype.getStreetaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity.ADDRESS} returns this
 */
proto.cattlechain.FarmIdentity.ADDRESS.prototype.setStreetaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cattlechain.FarmIdentity.LOCATION.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cattlechain.FarmIdentity.LOCATION.prototype.toObject = function(opt_includeInstance) {
  return proto.cattlechain.FarmIdentity.LOCATION.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cattlechain.FarmIdentity.LOCATION} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.LOCATION.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    coordinatesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cattlechain.FarmIdentity.LOCATION}
 */
proto.cattlechain.FarmIdentity.LOCATION.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cattlechain.FarmIdentity.LOCATION;
  return proto.cattlechain.FarmIdentity.LOCATION.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cattlechain.FarmIdentity.LOCATION} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cattlechain.FarmIdentity.LOCATION}
 */
proto.cattlechain.FarmIdentity.LOCATION.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setCoordinatesList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cattlechain.FarmIdentity.LOCATION.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cattlechain.FarmIdentity.LOCATION.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cattlechain.FarmIdentity.LOCATION} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.LOCATION.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCoordinatesList();
  if (f.length > 0) {
    writer.writePackedFloat(
      2,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.LOCATION.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity.LOCATION} returns this
 */
proto.cattlechain.FarmIdentity.LOCATION.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated float coordinates = 2;
 * @return {!Array<number>}
 */
proto.cattlechain.FarmIdentity.LOCATION.prototype.getCoordinatesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.cattlechain.FarmIdentity.LOCATION} returns this
 */
proto.cattlechain.FarmIdentity.LOCATION.prototype.setCoordinatesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.cattlechain.FarmIdentity.LOCATION} returns this
 */
proto.cattlechain.FarmIdentity.LOCATION.prototype.addCoordinates = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cattlechain.FarmIdentity.LOCATION} returns this
 */
proto.cattlechain.FarmIdentity.LOCATION.prototype.clearCoordinatesList = function() {
  return this.setCoordinatesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.prototype.toObject = function(opt_includeInstance) {
  return proto.cattlechain.FarmIdentity.RELATEDSOURCE.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cattlechain.FarmIdentity.RELATEDSOURCE} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.toObject = function(includeInstance, msg) {
  var f, obj = {
    application: jspb.Message.getFieldWithDefault(msg, 1, ""),
    applicationentityid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cattlechain.FarmIdentity.RELATEDSOURCE}
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cattlechain.FarmIdentity.RELATEDSOURCE;
  return proto.cattlechain.FarmIdentity.RELATEDSOURCE.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cattlechain.FarmIdentity.RELATEDSOURCE} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cattlechain.FarmIdentity.RELATEDSOURCE}
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplication(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplicationentityid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cattlechain.FarmIdentity.RELATEDSOURCE.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cattlechain.FarmIdentity.RELATEDSOURCE} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApplication();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApplicationentityid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string application = 1;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.prototype.getApplication = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity.RELATEDSOURCE} returns this
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.prototype.setApplication = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string applicationEntityId = 2;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.prototype.getApplicationentityid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity.RELATEDSOURCE} returns this
 */
proto.cattlechain.FarmIdentity.RELATEDSOURCE.prototype.setApplicationentityid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string dataCreated = 3;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.prototype.getDatacreated = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.setDatacreated = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string dataModified = 4;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.prototype.getDatamodified = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.setDatamodified = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional CONTACTPOINT contactPoint = 7;
 * @return {?proto.cattlechain.FarmIdentity.CONTACTPOINT}
 */
proto.cattlechain.FarmIdentity.prototype.getContactpoint = function() {
  return /** @type{?proto.cattlechain.FarmIdentity.CONTACTPOINT} */ (
    jspb.Message.getWrapperField(this, proto.cattlechain.FarmIdentity.CONTACTPOINT, 7));
};


/**
 * @param {?proto.cattlechain.FarmIdentity.CONTACTPOINT|undefined} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
*/
proto.cattlechain.FarmIdentity.prototype.setContactpoint = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.clearContactpoint = function() {
  return this.setContactpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cattlechain.FarmIdentity.prototype.hasContactpoint = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string ownedBy = 8;
 * @return {string}
 */
proto.cattlechain.FarmIdentity.prototype.getOwnedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.setOwnedby = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional ADDRESS address = 9;
 * @return {?proto.cattlechain.FarmIdentity.ADDRESS}
 */
proto.cattlechain.FarmIdentity.prototype.getAddress = function() {
  return /** @type{?proto.cattlechain.FarmIdentity.ADDRESS} */ (
    jspb.Message.getWrapperField(this, proto.cattlechain.FarmIdentity.ADDRESS, 9));
};


/**
 * @param {?proto.cattlechain.FarmIdentity.ADDRESS|undefined} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
*/
proto.cattlechain.FarmIdentity.prototype.setAddress = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.clearAddress = function() {
  return this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cattlechain.FarmIdentity.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional LOCATION location = 10;
 * @return {?proto.cattlechain.FarmIdentity.LOCATION}
 */
proto.cattlechain.FarmIdentity.prototype.getLocation = function() {
  return /** @type{?proto.cattlechain.FarmIdentity.LOCATION} */ (
    jspb.Message.getWrapperField(this, proto.cattlechain.FarmIdentity.LOCATION, 10));
};


/**
 * @param {?proto.cattlechain.FarmIdentity.LOCATION|undefined} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
*/
proto.cattlechain.FarmIdentity.prototype.setLocation = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.clearLocation = function() {
  return this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cattlechain.FarmIdentity.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated RELATEDSOURCE relatedSource = 11;
 * @return {!Array<!proto.cattlechain.FarmIdentity.RELATEDSOURCE>}
 */
proto.cattlechain.FarmIdentity.prototype.getRelatedsourceList = function() {
  return /** @type{!Array<!proto.cattlechain.FarmIdentity.RELATEDSOURCE>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cattlechain.FarmIdentity.RELATEDSOURCE, 11));
};


/**
 * @param {!Array<!proto.cattlechain.FarmIdentity.RELATEDSOURCE>} value
 * @return {!proto.cattlechain.FarmIdentity} returns this
*/
proto.cattlechain.FarmIdentity.prototype.setRelatedsourceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.cattlechain.FarmIdentity.RELATEDSOURCE=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cattlechain.FarmIdentity.RELATEDSOURCE}
 */
proto.cattlechain.FarmIdentity.prototype.addRelatedsource = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.cattlechain.FarmIdentity.RELATEDSOURCE, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cattlechain.FarmIdentity} returns this
 */
proto.cattlechain.FarmIdentity.prototype.clearRelatedsourceList = function() {
  return this.setRelatedsourceList([]);
};


goog.object.extend(exports, proto.cattlechain);
